### ISSUE TITLE
website does not load in mainstage

### ISSUE THREAD

**Issue by ldafner** [Esri/map-journal-storytelling-template-js#17]
I tried adding a website in the main stage... http://www.allaboutbirds.org/guide/Eastern_Bluebird/id

Result... grey background 
![image](https://cloud.githubusercontent.com/assets/6750343/5902635/1c389590-a54a-11e4-8635-af0f68b643aa.png)

i took a look at the console and found this error message...

<code>Mixed Content: The page at 'https://neod.maps.arcgis.com/apps/MapJournal/index.html?appid=c8999ff5930f486189a439bc0e951148' was loaded over HTTPS, but requested an insecure resource 'http://www.allaboutbirds.org/guide/Eastern_Bluebird/id'. This request has been blocked; the content must be served over HTTPS.</code>

Thoughts on fixing this issue?

**Comment by glazou** [comment]
Mixing http and https content can be tricky depending on the configuration of the website you are trying to include. In your case that website doesn't load over https 
https://www.allaboutbirds.org/guide/Eastern_Bluebird/id so you need to load it on http like you are doing. The browser trow a security error because the website is doing unsecure stuff.

In that case your only solution is to use Map Journal over http http://www.arcgis.com/apps/MapJournal/?fromScratch

Your Organization settings may not allow that. If it doesn't you won't be able to include that website.

**Comment by ldafner** [comment]
Thanks Greg!

**Comment by ldafner** [comment]
So, if I access that link and then log in to my organization from there I should be able to override the https security settings in my org?

**Comment by glazou** [comment]
I'm not sure exactly how it works. I know there is settings to force an Organization to always use https. In your case looks like http://neod.maps.arcgis.com/apps/MapJournal/index.html?appid=c8999ff5930f486189a439bc0e951148 works
