### ISSUE TITLE
Allow Map features/popup to navigate to specific section

### ISSUE THREAD

**Issue by glazou** [Esri/map-journal-storytelling-template-js#5]
This issue track that popular enhancement request. As of today that feature is not in the near future roadmap.

The V1.1 planned for September 23rd will allow to create links (in the panels) to navigate between sections. With that enhancement it will be possible for developers to customize Map Journal to add specific behavior to certain map to allow it's features to drive the Journal.

**Comment by glazou** [comment]
A workflow to implement this through a customization has been documented at https://github.com/Esri/map-journal-storytelling-template-js#link-between-sections
Also note the following article that focus on navigation though links that can be used as an introduction to the process https://developerscorner.storymaps.arcgis.com/adding-links-to-sections-in-story-map-journal-a875bb45fdd5#.gbtmnmp4l

**Comment by upcamogie** [comment]
Is there a way to specifically navigate to the side content page and not the map page? I am working with a mobile view and i'd like to have the content panel (the #details) be loaded instead of the map page. I have my 'home' button  configured like this

 <a class="btn-blue" onclick="require(['dojo/topic'], function(topic){ topic.publish('story-navigate-section', 0); });" target="_blank">Home</a>

It may just be a wish list thing for working with whatever the app looks like responsive design but I figured I'd ask. thanks

**Comment by glazou** [comment]
Yes, you can do that using

```
<p><a onclick="require(['dojo/topic'], function(topic){ topic.publish('story-navigate-section', 0); setTimeout(function(){ location.hash = 'detail'; }, 50);  });">link to home</a></p>
```

**Comment by upcamogie** [comment]
that looks great for my purposes....thanks!

**Comment by oevans** [comment]
It is now possible to create a link to another section in the builder _without_ code. See this blog post for more info:
https://blogs.esri.com/esri/arcgis/2016/09/14/whats-new-story-maps-september-2016/

**Comment by RupertEssinger** [comment]
Hi Owen, this enhancement is to allow navigation by clicking on a feature on the map. That would still be a good enhancement as an option in MJ for place based stories.
