### ISSUE TITLE
code line missing

### ISSUE THREAD

**Issue by iodogani** [Esri/map-journal-storytelling-template-js#55]
i think there's a line missing in common/core.js line 97.

it should be 

         app.indexCfg = {
					appid: app.indexCfg.appid, // this is the one missing
					proxyurl: app.indexCfg.proxyurl,
					sharingurl: app.indexCfg.sharingurl,
					username: app.indexCfg.username,
					password: app.indexCfg.password

**Comment by glazou** [comment]
Thanks for the feedback, if this works for you that's great but I won't include that change. 

The idea by not having that line is that it doesn't let you configure the app in development in the same way that when the application is build (notice that there is a conditional before that block so that code is only executed in development mode https://github.com/Esri/map-journal-storytelling-template-js/blob/master/src/app/storymaps/common/Core.js#L96). 

In development you have to use the url parameter `appid=` while in production you will use the configuration in index.html, see https://github.com/Esri/map-journal-storytelling-template-js#how-to-use-the-application-from-the-source-code . This is a little security to avoid users deploying the development version of the application in production without knowing it.

I know the error message in development was not really clear that you needed to use appid, so we are making that better for next release.

**Comment by iodogani** [comment]
thank you very much for your help,
I appreciate it,
kind regards,

Io

On Wed, Feb 17, 2016 at 6:18 PM, glazou <notifications@github.com> wrote:

> Closed #55
> <https://github.com/Esri/map-journal-storytelling-template-js/issues/55>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/map-journal-storytelling-template-js/issues/55#event-553798408>
> .
>



-- 
Δογάνη Δ. Ιώ
Dogani D. Io
Student Tei Athens -Energy Technology
 & City University of Seattle- Systems development
