### ISSUE TITLE
"Section=" URL parameter doesn't always load/scroll to proper section

### ISSUE THREAD

**Issue by InfiniteCoop** [Esri/map-journal-storytelling-template-js#61]
This issue is pretty inconsistent both between and within stories, and so I haven't been able to isolate specific causes. Sometimes, the story will scroll to the proper section, but it won't actually activate that section (below).

Other times, the proper mainstage panel/map action will load properly, but the sidebar won't. 

Sometimes, it just doesn't work at all. Sometimes refreshing the page a bunch seems to solve the problem. In any case, it interferes with the ability to share a specific section (if that section sharing is enabled in the settings), or navigating to a section programmatically. I encountered these issues in Chrome and Firefox (Mac).

**Comment by InfiniteCoop** [comment]
![section-scroll1](https://cloud.githubusercontent.com/assets/3599733/14053773/1d292cc2-f2aa-11e5-8e62-aa55f9769912.jpg)
![section-scroll2](https://cloud.githubusercontent.com/assets/3599733/14053774/1dd4b0f6-f2aa-11e5-80fc-80b27b4dfa4a.jpg)
![section-scroll3](https://cloud.githubusercontent.com/assets/3599733/14053775/1dd59c1e-f2aa-11e5-8fe0-cf00a9936974.jpg)

**Comment by glazou** [comment]
It's a know issue/limitation we never got time to fix. If you need to use index parameter, the Floating panel is the only 100% safe layout. Side Panel is safe if you don't have any image in your section description (It should not happen with video/web page but haven't checked recently).

The Main Stage should always load properly (until you scroll then depending on the invalid scroll position it will load that section). 

When you reload the page, your browser have image cached so that's why it works sometimes...

**Comment by glazou** [comment]
The ability to create links that 'scroll' the story to a specific section is getting deprecated for the Side Panel layout due to this issue. This is still possible with the Floating Panel layout. 
Existing stories will not be impacted.
