### ISSUE TITLE
Allow Story Map Template show the related table info in the popup window

### ISSUE THREAD

**Issue by goldenlimit** [Esri/map-journal-storytelling-template-js#73]
When using Story Map template the related table information doesn't show in the popup, however in AGOL webmap and Web AppBuilder template, the related table info are all show in the popup

![webmap_relatedtable](https://cloud.githubusercontent.com/assets/5265346/22043745/f5871f74-dcc5-11e6-9018-0d8fbf4666c7.JPG)
Here is the sample webmap that shows the related table info in popup window: http://ess.maps.arcgis.com/home/item.html?id=9ce07d983dde49e49a827c640238af31

------------------------------------------------------------------------------------------------------

![wab_relatedtable](https://cloud.githubusercontent.com/assets/5265346/22043755/007e92b8-dcc6-11e6-8b60-6e0845bae610.JPG)
Here is the WAB template shows that related table info show in popup window: http://ess.maps.arcgis.com/home/item.html?id=7da68711d68c4338b4585d15d8ccb6ac

------------------------------------------------------------------------------------------------------

![storymap_relatedtable](https://cloud.githubusercontent.com/assets/5265346/22043762/08ce1b82-dcc6-11e6-8674-dd8292a5d8ec.JPG)
Here is the Story Map Journal App shows that the related table info does not show in popup: http://ess.maps.arcgis.com/home/item.html?id=d04cf21a615d4c1594810cc47d0d3887

Logged this defect: ENH-000102163

**Comment by oevans** [comment]
Thanks for your feedback. This is expected behavior; the pop-up display in story maps is simplified to reduce the potential for overwhelming a typical reader with information, buttons, and links.

One of the primary design goals for story maps is to make them easy for readers to understand and use. _Related records is a technical concept_ that is used by data analysts to find patterns. So, while it is a function that GIS professionals find invaluable, it is not a storytelling tool that is helpful to a broad audience.

If there is a story that is being created for a technical audience who understand relate records and how to use them, authors can easily embed into their story map (using the "web page" option) Web AppBuilder or other ArcGIS app template that provides an experience for viewing related records; however, at this time we have no plans to enable browsing of related records natively in story maps.
